/*
 *  Copyright (C) 2008-2012 Nils Hoffmann
 *  Nils.Hoffmann A T CeBiTec.Uni-Bielefeld.DE
 *
 *  This file is part of Cross/Maltcms.
 *
 *  Cross/Maltcms is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Cross/Maltcms is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with Cross/Maltcms.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  $Id$
 */
package maltcms.ui.charts;

/**
 * 
 * @author hoffmann
 */
public class VariableSelectionPanel extends javax.swing.JPanel {

	/**
     * 
     */
	private static final long serialVersionUID = -1731263966310777412L;

	/** Creates new form VariableSelectionPanel */
	public VariableSelectionPanel() {
		initComponents();
	}

	public void setAvailableVariables(String[] s) {
		this.jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(s));
		this.jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(s));
	}

	public String getSelectedDomainVariable() {
		if (this.jComboBox1.isEnabled()) {
			return (String) this.jComboBox1.getSelectedItem();
		}
		return "";
	}

	public String getSelectedValuesVariable() {
		return (String) this.jComboBox3.getSelectedItem();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jComboBox1 = new javax.swing.JComboBox();
		jCheckBox1 = new javax.swing.JCheckBox();
		jLabel1 = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		jComboBox3 = new javax.swing.JComboBox();
		jLabel4 = new javax.swing.JLabel();

		jPanel1.setBorder(javax.swing.BorderFactory
		        .createTitledBorder("Domain axis"));

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
		        "Item 1", "Item 2", "Item 3", "Item 4" }));
		jComboBox1.setEnabled(false);

		jCheckBox1.setText("Use separate variable for domain axis values");
		jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox1ActionPerformed(evt);
			}
		});

		jLabel1.setText("Variable for domain values");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
		        jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
		        .setHorizontalGroup(jPanel1Layout
		                .createParallelGroup(
		                        javax.swing.GroupLayout.Alignment.LEADING)
		                .addGroup(
		                        jPanel1Layout
		                                .createSequentialGroup()
		                                .addContainerGap()
		                                .addGroup(
		                                        jPanel1Layout
		                                                .createParallelGroup(
		                                                        javax.swing.GroupLayout.Alignment.LEADING)
		                                                .addComponent(
		                                                        jCheckBox1)
		                                                .addGroup(
		                                                        javax.swing.GroupLayout.Alignment.TRAILING,
		                                                        jPanel1Layout
		                                                                .createSequentialGroup()
		                                                                .addComponent(
		                                                                        jLabel1)
		                                                                .addPreferredGap(
		                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                                                                .addComponent(
		                                                                        jComboBox1,
		                                                                        0,
		                                                                        205,
		                                                                        Short.MAX_VALUE)))
		                                .addContainerGap()));
		jPanel1Layout
		        .setVerticalGroup(jPanel1Layout
		                .createParallelGroup(
		                        javax.swing.GroupLayout.Alignment.LEADING)
		                .addGroup(
		                        javax.swing.GroupLayout.Alignment.TRAILING,
		                        jPanel1Layout
		                                .createSequentialGroup()
		                                .addComponent(jCheckBox1)
		                                .addPreferredGap(
		                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                                .addGroup(
		                                        jPanel1Layout
		                                                .createParallelGroup(
		                                                        javax.swing.GroupLayout.Alignment.BASELINE)
		                                                .addComponent(
		                                                        jComboBox1,
		                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
		                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
		                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
		                                                .addComponent(jLabel1))
		                                .addContainerGap(
		                                        javax.swing.GroupLayout.DEFAULT_SIZE,
		                                        Short.MAX_VALUE)));

		jPanel2.setBorder(javax.swing.BorderFactory
		        .createTitledBorder("Value axis"));

		jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
		        "Item 1", "Item 2", "Item 3", "Item 4" }));

		jLabel4.setText("Variable for data values");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
		        jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
		        .setHorizontalGroup(jPanel2Layout
		                .createParallelGroup(
		                        javax.swing.GroupLayout.Alignment.LEADING)
		                .addGroup(
		                        jPanel2Layout
		                                .createSequentialGroup()
		                                .addContainerGap()
		                                .addComponent(
		                                        jLabel4,
		                                        javax.swing.GroupLayout.PREFERRED_SIZE,
		                                        146,
		                                        javax.swing.GroupLayout.PREFERRED_SIZE)
		                                .addPreferredGap(
		                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
		                                .addComponent(jComboBox3, 0, 204,
		                                        Short.MAX_VALUE)
		                                .addContainerGap()));
		jPanel2Layout
		        .setVerticalGroup(jPanel2Layout
		                .createParallelGroup(
		                        javax.swing.GroupLayout.Alignment.LEADING)
		                .addGroup(
		                        jPanel2Layout
		                                .createSequentialGroup()
		                                .addGroup(
		                                        jPanel2Layout
		                                                .createParallelGroup(
		                                                        javax.swing.GroupLayout.Alignment.BASELINE)
		                                                .addComponent(
		                                                        jComboBox3,
		                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
		                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
		                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
		                                                .addComponent(jLabel4))
		                                .addContainerGap(
		                                        javax.swing.GroupLayout.DEFAULT_SIZE,
		                                        Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout
		        .setHorizontalGroup(layout
		                .createParallelGroup(
		                        javax.swing.GroupLayout.Alignment.LEADING)
		                .addGroup(
		                        javax.swing.GroupLayout.Alignment.TRAILING,
		                        layout
		                                .createSequentialGroup()
		                                .addContainerGap()
		                                .addGroup(
		                                        layout
		                                                .createParallelGroup(
		                                                        javax.swing.GroupLayout.Alignment.LEADING)
		                                                .addComponent(
		                                                        jPanel1,
		                                                        javax.swing.GroupLayout.Alignment.TRAILING,
		                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
		                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
		                                                        Short.MAX_VALUE)
		                                                .addComponent(
		                                                        jPanel2,
		                                                        javax.swing.GroupLayout.Alignment.TRAILING,
		                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
		                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
		                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
		                                .addContainerGap()));
		layout
		        .setVerticalGroup(layout
		                .createParallelGroup(
		                        javax.swing.GroupLayout.Alignment.LEADING)
		                .addGroup(
		                        layout
		                                .createSequentialGroup()
		                                .addContainerGap()
		                                .addComponent(
		                                        jPanel1,
		                                        javax.swing.GroupLayout.PREFERRED_SIZE,
		                                        javax.swing.GroupLayout.DEFAULT_SIZE,
		                                        javax.swing.GroupLayout.PREFERRED_SIZE)
		                                .addPreferredGap(
		                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                                .addComponent(
		                                        jPanel2,
		                                        javax.swing.GroupLayout.PREFERRED_SIZE,
		                                        62,
		                                        javax.swing.GroupLayout.PREFERRED_SIZE)
		                                .addContainerGap(
		                                        javax.swing.GroupLayout.DEFAULT_SIZE,
		                                        Short.MAX_VALUE)));
	}// </editor-fold>//GEN-END:initComponents

	private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jCheckBox1ActionPerformed
		if (this.jCheckBox1.isSelected()) {
			this.jComboBox1.setEnabled(true);
		} else {
			this.jComboBox1.setEnabled(false);
		}
	}// GEN-LAST:event_jCheckBox1ActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JCheckBox jCheckBox1;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JComboBox jComboBox3;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	// End of variables declaration//GEN-END:variables

}
