/*
 * $Id$
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.1-646
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2008.10.14 at 08:55:46 AM CEST
//

package maltcms.io.xml.mzData;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

/**
 * Extension of binary data group for m/z and intensity values
 * 
 * <p>
 * Java class for peakListBinaryType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;peakListBinaryType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;group ref=&quot;{}binaryDataGroup&quot;/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "peakListBinaryType", propOrder = { "data" })
public class PeakListBinaryType {

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType&gt;
	 *   &lt;simpleContent&gt;
	 *     &lt;extension base=&quot;&lt;http://www.w3.org/2001/XMLSchema&gt;base64Binary&quot;&gt;
	 *       &lt;attribute name=&quot;precision&quot; use=&quot;required&quot;&gt;
	 *         &lt;simpleType&gt;
	 *           &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;&gt;
	 *             &lt;enumeration value=&quot;32&quot;/&gt;
	 *             &lt;enumeration value=&quot;64&quot;/&gt;
	 *           &lt;/restriction&gt;
	 *         &lt;/simpleType&gt;
	 *       &lt;/attribute&gt;
	 *       &lt;attribute name=&quot;endian&quot; use=&quot;required&quot;&gt;
	 *         &lt;simpleType&gt;
	 *           &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;&gt;
	 *             &lt;enumeration value=&quot;big&quot;/&gt;
	 *             &lt;enumeration value=&quot;little&quot;/&gt;
	 *           &lt;/restriction&gt;
	 *         &lt;/simpleType&gt;
	 *       &lt;/attribute&gt;
	 *       &lt;attribute name=&quot;length&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot; /&gt;
	 *     &lt;/extension&gt;
	 *   &lt;/simpleContent&gt;
	 * &lt;/complexType&gt;
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "value" })
	public static class Data {

		@XmlValue
		protected byte[] value;
		@XmlAttribute(required = true)
		protected String precision;
		@XmlAttribute(required = true)
		protected String endian;
		@XmlAttribute(required = true)
		protected int length;

		/**
		 * Gets the value of the endian property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getEndian() {
			return this.endian;
		}

		/**
		 * Gets the value of the length property.
		 * 
		 */
		public int getLength() {
			return this.length;
		}

		/**
		 * Gets the value of the precision property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getPrecision() {
			return this.precision;
		}

		/**
		 * Gets the value of the value property.
		 * 
		 * @return possible object is byte[]
		 */
		public byte[] getValue() {
			return this.value;
		}

		/**
		 * Sets the value of the endian property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setEndian(final String value) {
			this.endian = value;
		}

		/**
		 * Sets the value of the length property.
		 * 
		 */
		public void setLength(final int value) {
			this.length = value;
		}

		/**
		 * Sets the value of the precision property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setPrecision(final String value) {
			this.precision = value;
		}

		/**
		 * Sets the value of the value property.
		 * 
		 * @param value
		 *            allowed object is byte[]
		 */
		public void setValue(final byte[] value) {
			this.value = (value);
		}

	}

	@XmlElement(required = true)
	protected PeakListBinaryType.Data data;

	/**
	 * Gets the value of the data property.
	 * 
	 * @return possible object is {@link PeakListBinaryType.Data }
	 * 
	 */
	public PeakListBinaryType.Data getData() {
		return this.data;
	}

	/**
	 * Sets the value of the data property.
	 * 
	 * @param value
	 *            allowed object is {@link PeakListBinaryType.Data }
	 * 
	 */
	public void setData(final PeakListBinaryType.Data value) {
		this.data = value;
	}

}
