/*
 * $Id$
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.1-646
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2008.10.14 at 08:55:16 AM CEST
//

package maltcms.io.xml.mzML;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * Scan or acquisition from original raw file used to create this peak list, as
 * specified in sourceFile.
 * 
 * <p>
 * Java class for AcquisitionType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;AcquisitionType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base=&quot;{http://psi.hupo.org/schema_revision/mzML_1.0.0}ParamGroupType&quot;&gt;
 *       &lt;attribute name=&quot;number&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot; /&gt;
 *       &lt;attribute name=&quot;spectrumRef&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}IDREF&quot; /&gt;
 *       &lt;attribute name=&quot;sourceFileRef&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}IDREF&quot; /&gt;
 *       &lt;attribute name=&quot;externalNativeID&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
 *       &lt;attribute name=&quot;externalSpectrumID&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AcquisitionType")
public class AcquisitionType extends ParamGroupType {

	@XmlAttribute(required = true)
	protected int number;
	@XmlAttribute
	@XmlIDREF
	@XmlSchemaType(name = "IDREF")
	protected Object spectrumRef;
	@XmlAttribute
	@XmlIDREF
	@XmlSchemaType(name = "IDREF")
	protected Object sourceFileRef;
	@XmlAttribute
	protected String externalNativeID;
	@XmlAttribute
	protected String externalSpectrumID;

	/**
	 * Gets the value of the externalNativeID property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getExternalNativeID() {
		return this.externalNativeID;
	}

	/**
	 * Gets the value of the externalSpectrumID property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getExternalSpectrumID() {
		return this.externalSpectrumID;
	}

	/**
	 * Gets the value of the number property.
	 * 
	 */
	public int getNumber() {
		return this.number;
	}

	/**
	 * Gets the value of the sourceFileRef property.
	 * 
	 * @return possible object is {@link Object }
	 * 
	 */
	public Object getSourceFileRef() {
		return this.sourceFileRef;
	}

	/**
	 * Gets the value of the spectrumRef property.
	 * 
	 * @return possible object is {@link Object }
	 * 
	 */
	public Object getSpectrumRef() {
		return this.spectrumRef;
	}

	/**
	 * Sets the value of the externalNativeID property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setExternalNativeID(final String value) {
		this.externalNativeID = value;
	}

	/**
	 * Sets the value of the externalSpectrumID property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setExternalSpectrumID(final String value) {
		this.externalSpectrumID = value;
	}

	/**
	 * Sets the value of the number property.
	 * 
	 */
	public void setNumber(final int value) {
		this.number = value;
	}

	/**
	 * Sets the value of the sourceFileRef property.
	 * 
	 * @param value
	 *            allowed object is {@link Object }
	 * 
	 */
	public void setSourceFileRef(final Object value) {
		this.sourceFileRef = value;
	}

	/**
	 * Sets the value of the spectrumRef property.
	 * 
	 * @param value
	 *            allowed object is {@link Object }
	 * 
	 */
	public void setSpectrumRef(final Object value) {
		this.spectrumRef = value;
	}

}
