/*
 * $Id$
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.1-646
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2008.10.14 at 08:55:16 AM CEST
//

package maltcms.io.xml.mzML;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * List with the different components used in the mass spectrometer. At least
 * one source, one mass analyzer and one detector need to be specified.
 * 
 * <p>
 * Java class for ComponentListType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;ComponentListType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence maxOccurs=&quot;unbounded&quot; minOccurs=&quot;3&quot;&gt;
 *         &lt;choice&gt;
 *           &lt;element name=&quot;source&quot; type=&quot;{http://psi.hupo.org/schema_revision/mzML_1.0.0}ComponentType&quot;/&gt;
 *           &lt;element name=&quot;analyzer&quot; type=&quot;{http://psi.hupo.org/schema_revision/mzML_1.0.0}ComponentType&quot;/&gt;
 *           &lt;element name=&quot;detector&quot; type=&quot;{http://psi.hupo.org/schema_revision/mzML_1.0.0}ComponentType&quot;/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name=&quot;count&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}nonNegativeInteger&quot; /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComponentListType", propOrder = { "sourceOrAnalyzerOrDetector" })
public class ComponentListType {

	@XmlElementRefs( {
	        @XmlElementRef(name = "source", namespace = "http://psi.hupo.org/schema_revision/mzML_1.0.0", type = JAXBElement.class),
	        @XmlElementRef(name = "analyzer", namespace = "http://psi.hupo.org/schema_revision/mzML_1.0.0", type = JAXBElement.class),
	        @XmlElementRef(name = "detector", namespace = "http://psi.hupo.org/schema_revision/mzML_1.0.0", type = JAXBElement.class) })
	protected List<JAXBElement<ComponentType>> sourceOrAnalyzerOrDetector;
	@XmlAttribute(required = true)
	@XmlSchemaType(name = "nonNegativeInteger")
	protected BigInteger count;

	/**
	 * Gets the value of the count property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getCount() {
		return this.count;
	}

	/**
	 * Gets the value of the sourceOrAnalyzerOrDetector property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the sourceOrAnalyzerOrDetector property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getSourceOrAnalyzerOrDetector().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link JAXBElement }{@code <}{@link ComponentType }{@code >}
	 * {@link JAXBElement }{@code <}{@link ComponentType }{@code >}
	 * {@link JAXBElement }{@code <}{@link ComponentType }{@code >}
	 * 
	 * 
	 */
	public List<JAXBElement<ComponentType>> getSourceOrAnalyzerOrDetector() {
		if (this.sourceOrAnalyzerOrDetector == null) {
			this.sourceOrAnalyzerOrDetector = new ArrayList<JAXBElement<ComponentType>>();
		}
		return this.sourceOrAnalyzerOrDetector;
	}

	/**
	 * Sets the value of the count property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setCount(final BigInteger value) {
		this.count = value;
	}

}
