/*
 * $Id$
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.1-646
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2008.10.14 at 08:55:16 AM CEST
//

package maltcms.io.xml.mzML;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * Description of a particular hardware configuration of a mass spectrometer.
 * Each configuration must have one (and only one) of the three different
 * components used for an analysis. For hybrid instruments, such as an LTQ-FT,
 * there must be one configuration for each permutation of the components that
 * is used in the document. For software configuration, use a
 * ReferenceableParamGroup element.
 * 
 * <p>
 * Java class for InstrumentConfigurationType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;InstrumentConfigurationType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base=&quot;{http://psi.hupo.org/schema_revision/mzML_1.0.0}ParamGroupType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element name=&quot;componentList&quot; type=&quot;{http://psi.hupo.org/schema_revision/mzML_1.0.0}ComponentListType&quot;/&gt;
 *         &lt;element name=&quot;softwareRef&quot; type=&quot;{http://psi.hupo.org/schema_revision/mzML_1.0.0}SoftwareRefType&quot; minOccurs=&quot;0&quot;/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name=&quot;id&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}ID&quot; /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InstrumentConfigurationType", propOrder = { "componentList",
        "softwareRef" })
public class InstrumentConfigurationType extends ParamGroupType {

	@XmlElement(required = true)
	protected ComponentListType componentList;
	protected SoftwareRefType softwareRef;
	@XmlAttribute(required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlID
	@XmlSchemaType(name = "ID")
	protected String id;

	/**
	 * Gets the value of the componentList property.
	 * 
	 * @return possible object is {@link ComponentListType }
	 * 
	 */
	public ComponentListType getComponentList() {
		return this.componentList;
	}

	/**
	 * Gets the value of the id property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * Gets the value of the softwareRef property.
	 * 
	 * @return possible object is {@link SoftwareRefType }
	 * 
	 */
	public SoftwareRefType getSoftwareRef() {
		return this.softwareRef;
	}

	/**
	 * Sets the value of the componentList property.
	 * 
	 * @param value
	 *            allowed object is {@link ComponentListType }
	 * 
	 */
	public void setComponentList(final ComponentListType value) {
		this.componentList = value;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setId(final String value) {
		this.id = value;
	}

	/**
	 * Sets the value of the softwareRef property.
	 * 
	 * @param value
	 *            allowed object is {@link SoftwareRefType }
	 * 
	 */
	public void setSoftwareRef(final SoftwareRefType value) {
		this.softwareRef = value;
	}

}
