/*
 * $Id$
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.1-646
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2008.10.14 at 08:55:16 AM CEST
//

package maltcms.io.xml.mzML;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the maltcms.io.xml.mzML package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups.
 * ArrayFactory methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _ComponentListTypeSource_QNAME = new QName(
	        "http://psi.hupo.org/schema_revision/mzML_1.0.0", "source");
	private final static QName _ComponentListTypeDetector_QNAME = new QName(
	        "http://psi.hupo.org/schema_revision/mzML_1.0.0", "detector");
	private final static QName _ComponentListTypeAnalyzer_QNAME = new QName(
	        "http://psi.hupo.org/schema_revision/mzML_1.0.0", "analyzer");
	private final static QName _MzML_QNAME = new QName(
	        "http://psi.hupo.org/schema_revision/mzML_1.0.0", "mzML");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: maltcms.io.xml.mzML
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link AcquisitionListType }
	 * 
	 */
	public AcquisitionListType createAcquisitionListType() {
		return new AcquisitionListType();
	}

	/**
	 * Create an instance of {@link AcquisitionSettingsListType }
	 * 
	 */
	public AcquisitionSettingsListType createAcquisitionSettingsListType() {
		return new AcquisitionSettingsListType();
	}

	/**
	 * Create an instance of {@link AcquisitionSettingsType }
	 * 
	 */
	public AcquisitionSettingsType createAcquisitionSettingsType() {
		return new AcquisitionSettingsType();
	}

	/**
	 * Create an instance of {@link AcquisitionType }
	 * 
	 */
	public AcquisitionType createAcquisitionType() {
		return new AcquisitionType();
	}

	/**
	 * Create an instance of {@link BinaryDataArrayListType }
	 * 
	 */
	public BinaryDataArrayListType createBinaryDataArrayListType() {
		return new BinaryDataArrayListType();
	}

	/**
	 * Create an instance of {@link BinaryDataArrayType }
	 * 
	 */
	public BinaryDataArrayType createBinaryDataArrayType() {
		return new BinaryDataArrayType();
	}

	/**
	 * Create an instance of {@link ChromatogramListType }
	 * 
	 */
	public ChromatogramListType createChromatogramListType() {
		return new ChromatogramListType();
	}

	/**
	 * Create an instance of {@link ChromatogramType }
	 * 
	 */
	public ChromatogramType createChromatogramType() {
		return new ChromatogramType();
	}

	/**
	 * Create an instance of {@link ComponentListType }
	 * 
	 */
	public ComponentListType createComponentListType() {
		return new ComponentListType();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ComponentType }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://psi.hupo.org/schema_revision/mzML_1.0.0", name = "analyzer", scope = ComponentListType.class)
	public JAXBElement<ComponentType> createComponentListTypeAnalyzer(
	        final ComponentType value) {
		return new JAXBElement<ComponentType>(
		        ObjectFactory._ComponentListTypeAnalyzer_QNAME,
		        ComponentType.class, ComponentListType.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ComponentType }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://psi.hupo.org/schema_revision/mzML_1.0.0", name = "detector", scope = ComponentListType.class)
	public JAXBElement<ComponentType> createComponentListTypeDetector(
	        final ComponentType value) {
		return new JAXBElement<ComponentType>(
		        ObjectFactory._ComponentListTypeDetector_QNAME,
		        ComponentType.class, ComponentListType.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ComponentType }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://psi.hupo.org/schema_revision/mzML_1.0.0", name = "source", scope = ComponentListType.class)
	public JAXBElement<ComponentType> createComponentListTypeSource(
	        final ComponentType value) {
		return new JAXBElement<ComponentType>(
		        ObjectFactory._ComponentListTypeSource_QNAME,
		        ComponentType.class, ComponentListType.class, value);
	}

	/**
	 * Create an instance of {@link ComponentType }
	 * 
	 */
	public ComponentType createComponentType() {
		return new ComponentType();
	}

	/**
	 * Create an instance of {@link CVListType }
	 * 
	 */
	public CVListType createCVListType() {
		return new CVListType();
	}

	/**
	 * Create an instance of {@link CVParamType }
	 * 
	 */
	public CVParamType createCVParamType() {
		return new CVParamType();
	}

	/**
	 * Create an instance of {@link CVType }
	 * 
	 */
	public CVType createCVType() {
		return new CVType();
	}

	/**
	 * Create an instance of {@link DataProcessingListType }
	 * 
	 */
	public DataProcessingListType createDataProcessingListType() {
		return new DataProcessingListType();
	}

	/**
	 * Create an instance of {@link DataProcessingType }
	 * 
	 */
	public DataProcessingType createDataProcessingType() {
		return new DataProcessingType();
	}

	/**
	 * Create an instance of {@link FileDescriptionType }
	 * 
	 */
	public FileDescriptionType createFileDescriptionType() {
		return new FileDescriptionType();
	}

	/**
	 * Create an instance of {@link InstrumentConfigurationListType }
	 * 
	 */
	public InstrumentConfigurationListType createInstrumentConfigurationListType() {
		return new InstrumentConfigurationListType();
	}

	/**
	 * Create an instance of {@link InstrumentConfigurationType }
	 * 
	 */
	public InstrumentConfigurationType createInstrumentConfigurationType() {
		return new InstrumentConfigurationType();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link MzMLType }{@code
	 * >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://psi.hupo.org/schema_revision/mzML_1.0.0", name = "mzML")
	public JAXBElement<MzMLType> createMzML(final MzMLType value) {
		return new JAXBElement<MzMLType>(ObjectFactory._MzML_QNAME,
		        MzMLType.class, null, value);
	}

	/**
	 * Create an instance of {@link MzMLType }
	 * 
	 */
	public MzMLType createMzMLType() {
		return new MzMLType();
	}

	/**
	 * Create an instance of {@link ParamGroupType }
	 * 
	 */
	public ParamGroupType createParamGroupType() {
		return new ParamGroupType();
	}

	/**
	 * Create an instance of {@link PrecursorListType }
	 * 
	 */
	public PrecursorListType createPrecursorListType() {
		return new PrecursorListType();
	}

	/**
	 * Create an instance of {@link PrecursorType }
	 * 
	 */
	public PrecursorType createPrecursorType() {
		return new PrecursorType();
	}

	/**
	 * Create an instance of {@link ProcessingMethodType }
	 * 
	 */
	public ProcessingMethodType createProcessingMethodType() {
		return new ProcessingMethodType();
	}

	/**
	 * Create an instance of {@link ReferenceableParamGroupListType }
	 * 
	 */
	public ReferenceableParamGroupListType createReferenceableParamGroupListType() {
		return new ReferenceableParamGroupListType();
	}

	/**
	 * Create an instance of {@link ReferenceableParamGroupRefType }
	 * 
	 */
	public ReferenceableParamGroupRefType createReferenceableParamGroupRefType() {
		return new ReferenceableParamGroupRefType();
	}

	/**
	 * Create an instance of {@link ReferenceableParamGroupType }
	 * 
	 */
	public ReferenceableParamGroupType createReferenceableParamGroupType() {
		return new ReferenceableParamGroupType();
	}

	/**
	 * Create an instance of {@link RunType }
	 * 
	 */
	public RunType createRunType() {
		return new RunType();
	}

	/**
	 * Create an instance of {@link SampleListType }
	 * 
	 */
	public SampleListType createSampleListType() {
		return new SampleListType();
	}

	/**
	 * Create an instance of {@link SampleType }
	 * 
	 */
	public SampleType createSampleType() {
		return new SampleType();
	}

	/**
	 * Create an instance of {@link ScanType }
	 * 
	 */
	public ScanType createScanType() {
		return new ScanType();
	}

	/**
	 * Create an instance of {@link ScanWindowListType }
	 * 
	 */
	public ScanWindowListType createScanWindowListType() {
		return new ScanWindowListType();
	}

	/**
	 * Create an instance of {@link ScanWindowType }
	 * 
	 */
	public ScanWindowType createScanWindowType() {
		return new ScanWindowType();
	}

	/**
	 * Create an instance of {@link SelectedIonListType }
	 * 
	 */
	public SelectedIonListType createSelectedIonListType() {
		return new SelectedIonListType();
	}

	/**
	 * Create an instance of {@link SoftwareListType }
	 * 
	 */
	public SoftwareListType createSoftwareListType() {
		return new SoftwareListType();
	}

	/**
	 * Create an instance of {@link SoftwareParamType }
	 * 
	 */
	public SoftwareParamType createSoftwareParamType() {
		return new SoftwareParamType();
	}

	/**
	 * Create an instance of {@link SoftwareRefType }
	 * 
	 */
	public SoftwareRefType createSoftwareRefType() {
		return new SoftwareRefType();
	}

	/**
	 * Create an instance of {@link SoftwareType }
	 * 
	 */
	public SoftwareType createSoftwareType() {
		return new SoftwareType();
	}

	/**
	 * Create an instance of {@link SourceFileListType }
	 * 
	 */
	public SourceFileListType createSourceFileListType() {
		return new SourceFileListType();
	}

	/**
	 * Create an instance of {@link SourceFileRefListType }
	 * 
	 */
	public SourceFileRefListType createSourceFileRefListType() {
		return new SourceFileRefListType();
	}

	/**
	 * Create an instance of {@link SourceFileRefType }
	 * 
	 */
	public SourceFileRefType createSourceFileRefType() {
		return new SourceFileRefType();
	}

	/**
	 * Create an instance of {@link SourceFileType }
	 * 
	 */
	public SourceFileType createSourceFileType() {
		return new SourceFileType();
	}

	/**
	 * Create an instance of {@link SpectrumDescriptionType }
	 * 
	 */
	public SpectrumDescriptionType createSpectrumDescriptionType() {
		return new SpectrumDescriptionType();
	}

	/**
	 * Create an instance of {@link SpectrumListType }
	 * 
	 */
	public SpectrumListType createSpectrumListType() {
		return new SpectrumListType();
	}

	/**
	 * Create an instance of {@link SpectrumType }
	 * 
	 */
	public SpectrumType createSpectrumType() {
		return new SpectrumType();
	}

	/**
	 * Create an instance of {@link TargetListType }
	 * 
	 */
	public TargetListType createTargetListType() {
		return new TargetListType();
	}

	/**
	 * Create an instance of {@link UserParamType }
	 * 
	 */
	public UserParamType createUserParamType() {
		return new UserParamType();
	}

}
