/*
 * $Id$
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.1-646
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2008.10.14 at 08:55:16 AM CEST
//
@javax.xml.bind.annotation.XmlSchema(namespace = "http://psi.hupo.org/schema_revision/mzML_1.0.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package maltcms.io.xml.mzML;

