/*
 * $Id$
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.1-646
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2008.10.14 at 08:55:16 AM CEST
//

package maltcms.io.xml.mzML;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * Structure allowing the use of a controlled (cvParam) or uncontrolled
 * vocabulary (userParam), or a reference to a predefined set of these in this
 * mzML file (paramGroupRef).
 * 
 * <p>
 * Java class for ParamGroupType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;ParamGroupType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element name=&quot;referenceableParamGroupRef&quot; type=&quot;{http://psi.hupo.org/schema_revision/mzML_1.0.0}ReferenceableParamGroupRefType&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element name=&quot;cvParam&quot; type=&quot;{http://psi.hupo.org/schema_revision/mzML_1.0.0}CVParamType&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element name=&quot;userParam&quot; type=&quot;{http://psi.hupo.org/schema_revision/mzML_1.0.0}UserParamType&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ParamGroupType", propOrder = { "referenceableParamGroupRef",
        "cvParam", "userParam" })
@XmlSeeAlso( { SourceFileType.class, RunType.class, SampleType.class,
        AcquisitionListType.class, BinaryDataArrayType.class,
        ComponentType.class, InstrumentConfigurationType.class,
        SpectrumType.class, ProcessingMethodType.class, ChromatogramType.class,
        ScanType.class, SpectrumDescriptionType.class, AcquisitionType.class,
        AcquisitionSettingsType.class })
public class ParamGroupType {

	protected List<ReferenceableParamGroupRefType> referenceableParamGroupRef;
	protected List<CVParamType> cvParam;
	protected List<UserParamType> userParam;

	/**
	 * Gets the value of the cvParam property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the cvParam property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getCvParam().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link CVParamType }
	 * 
	 * 
	 */
	public List<CVParamType> getCvParam() {
		if (this.cvParam == null) {
			this.cvParam = new ArrayList<CVParamType>();
		}
		return this.cvParam;
	}

	/**
	 * Gets the value of the referenceableParamGroupRef property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the referenceableParamGroupRef property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getReferenceableParamGroupRef().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link ReferenceableParamGroupRefType }
	 * 
	 * 
	 */
	public List<ReferenceableParamGroupRefType> getReferenceableParamGroupRef() {
		if (this.referenceableParamGroupRef == null) {
			this.referenceableParamGroupRef = new ArrayList<ReferenceableParamGroupRefType>();
		}
		return this.referenceableParamGroupRef;
	}

	/**
	 * Gets the value of the userParam property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the userParam property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getUserParam().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link UserParamType }
	 * 
	 * 
	 */
	public List<UserParamType> getUserParam() {
		if (this.userParam == null) {
			this.userParam = new ArrayList<UserParamType>();
		}
		return this.userParam;
	}

}
