/*
 * $Id$
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.1-646
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2008.10.14 at 08:55:16 AM CEST
//

package maltcms.io.xml.mzML;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * A run in mzML should correspond to a single, consecutive and coherent set of
 * scans on an instrument.
 * 
 * <p>
 * Java class for RunType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;RunType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base=&quot;{http://psi.hupo.org/schema_revision/mzML_1.0.0}ParamGroupType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element name=&quot;sourceFileRefList&quot; type=&quot;{http://psi.hupo.org/schema_revision/mzML_1.0.0}SourceFileRefListType&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element name=&quot;spectrumList&quot; type=&quot;{http://psi.hupo.org/schema_revision/mzML_1.0.0}SpectrumListType&quot;/&gt;
 *         &lt;element name=&quot;chromatogramList&quot; type=&quot;{http://psi.hupo.org/schema_revision/mzML_1.0.0}ChromatogramListType&quot; minOccurs=&quot;0&quot;/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name=&quot;id&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}ID&quot; /&gt;
 *       &lt;attribute name=&quot;defaultInstrumentConfigurationRef&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}IDREF&quot; /&gt;
 *       &lt;attribute name=&quot;sampleRef&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}IDREF&quot; /&gt;
 *       &lt;attribute name=&quot;startTimeStamp&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}dateTime&quot; /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RunType", propOrder = { "sourceFileRefList", "spectrumList",
        "chromatogramList" })
public class RunType extends ParamGroupType {

	protected SourceFileRefListType sourceFileRefList;
	@XmlElement(required = true)
	protected SpectrumListType spectrumList;
	protected ChromatogramListType chromatogramList;
	@XmlAttribute(required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlID
	@XmlSchemaType(name = "ID")
	protected String id;
	@XmlAttribute(required = true)
	@XmlIDREF
	@XmlSchemaType(name = "IDREF")
	protected Object defaultInstrumentConfigurationRef;
	@XmlAttribute
	@XmlIDREF
	@XmlSchemaType(name = "IDREF")
	protected Object sampleRef;
	@XmlAttribute
	@XmlSchemaType(name = "dateTime")
	protected XMLGregorianCalendar startTimeStamp;

	/**
	 * Gets the value of the chromatogramList property.
	 * 
	 * @return possible object is {@link ChromatogramListType }
	 * 
	 */
	public ChromatogramListType getChromatogramList() {
		return this.chromatogramList;
	}

	/**
	 * Gets the value of the defaultInstrumentConfigurationRef property.
	 * 
	 * @return possible object is {@link Object }
	 * 
	 */
	public Object getDefaultInstrumentConfigurationRef() {
		return this.defaultInstrumentConfigurationRef;
	}

	/**
	 * Gets the value of the id property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * Gets the value of the sampleRef property.
	 * 
	 * @return possible object is {@link Object }
	 * 
	 */
	public Object getSampleRef() {
		return this.sampleRef;
	}

	/**
	 * Gets the value of the sourceFileRefList property.
	 * 
	 * @return possible object is {@link SourceFileRefListType }
	 * 
	 */
	public SourceFileRefListType getSourceFileRefList() {
		return this.sourceFileRefList;
	}

	/**
	 * Gets the value of the spectrumList property.
	 * 
	 * @return possible object is {@link SpectrumListType }
	 * 
	 */
	public SpectrumListType getSpectrumList() {
		return this.spectrumList;
	}

	/**
	 * Gets the value of the startTimeStamp property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getStartTimeStamp() {
		return this.startTimeStamp;
	}

	/**
	 * Sets the value of the chromatogramList property.
	 * 
	 * @param value
	 *            allowed object is {@link ChromatogramListType }
	 * 
	 */
	public void setChromatogramList(final ChromatogramListType value) {
		this.chromatogramList = value;
	}

	/**
	 * Sets the value of the defaultInstrumentConfigurationRef property.
	 * 
	 * @param value
	 *            allowed object is {@link Object }
	 * 
	 */
	public void setDefaultInstrumentConfigurationRef(final Object value) {
		this.defaultInstrumentConfigurationRef = value;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setId(final String value) {
		this.id = value;
	}

	/**
	 * Sets the value of the sampleRef property.
	 * 
	 * @param value
	 *            allowed object is {@link Object }
	 * 
	 */
	public void setSampleRef(final Object value) {
		this.sampleRef = value;
	}

	/**
	 * Sets the value of the sourceFileRefList property.
	 * 
	 * @param value
	 *            allowed object is {@link SourceFileRefListType }
	 * 
	 */
	public void setSourceFileRefList(final SourceFileRefListType value) {
		this.sourceFileRefList = value;
	}

	/**
	 * Sets the value of the spectrumList property.
	 * 
	 * @param value
	 *            allowed object is {@link SpectrumListType }
	 * 
	 */
	public void setSpectrumList(final SpectrumListType value) {
		this.spectrumList = value;
	}

	/**
	 * Sets the value of the startTimeStamp property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setStartTimeStamp(final XMLGregorianCalendar value) {
		this.startTimeStamp = value;
	}

}
