/*
 * $Id$
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.1-646
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2008.10.14 at 08:55:16 AM CEST
//

package maltcms.io.xml.mzML;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * The instrument's 'run time' parameters; common to the whole of this spectrum.
 * 
 * <p>
 * Java class for ScanType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;ScanType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base=&quot;{http://psi.hupo.org/schema_revision/mzML_1.0.0}ParamGroupType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element name=&quot;scanWindowList&quot; type=&quot;{http://psi.hupo.org/schema_revision/mzML_1.0.0}ScanWindowListType&quot;/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name=&quot;instrumentConfigurationRef&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}IDREF&quot; /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ScanType", propOrder = { "scanWindowList" })
public class ScanType extends ParamGroupType {

	@XmlElement(required = true)
	protected ScanWindowListType scanWindowList;
	@XmlAttribute
	@XmlIDREF
	@XmlSchemaType(name = "IDREF")
	protected Object instrumentConfigurationRef;

	/**
	 * Gets the value of the instrumentConfigurationRef property.
	 * 
	 * @return possible object is {@link Object }
	 * 
	 */
	public Object getInstrumentConfigurationRef() {
		return this.instrumentConfigurationRef;
	}

	/**
	 * Gets the value of the scanWindowList property.
	 * 
	 * @return possible object is {@link ScanWindowListType }
	 * 
	 */
	public ScanWindowListType getScanWindowList() {
		return this.scanWindowList;
	}

	/**
	 * Sets the value of the instrumentConfigurationRef property.
	 * 
	 * @param value
	 *            allowed object is {@link Object }
	 * 
	 */
	public void setInstrumentConfigurationRef(final Object value) {
		this.instrumentConfigurationRef = value;
	}

	/**
	 * Sets the value of the scanWindowList property.
	 * 
	 * @param value
	 *            allowed object is {@link ScanWindowListType }
	 * 
	 */
	public void setScanWindowList(final ScanWindowListType value) {
		this.scanWindowList = value;
	}

}
