/*
 * $Id$
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.1-646
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2008.10.14 at 08:55:16 AM CEST
//

package maltcms.io.xml.mzML;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * The structure that captures the generation of a peak list (including the
 * underlying acquisitions)
 * 
 * <p>
 * Java class for SpectrumType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;SpectrumType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base=&quot;{http://psi.hupo.org/schema_revision/mzML_1.0.0}ParamGroupType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element name=&quot;spectrumDescription&quot; type=&quot;{http://psi.hupo.org/schema_revision/mzML_1.0.0}SpectrumDescriptionType&quot;/&gt;
 *         &lt;element name=&quot;binaryDataArrayList&quot; type=&quot;{http://psi.hupo.org/schema_revision/mzML_1.0.0}BinaryDataArrayListType&quot; minOccurs=&quot;0&quot;/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name=&quot;id&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}ID&quot; /&gt;
 *       &lt;attribute name=&quot;nativeID&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
 *       &lt;attribute name=&quot;spotID&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
 *       &lt;attribute name=&quot;index&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}nonNegativeInteger&quot; /&gt;
 *       &lt;attribute name=&quot;defaultArrayLength&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot; /&gt;
 *       &lt;attribute name=&quot;dataProcessingRef&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}IDREF&quot; /&gt;
 *       &lt;attribute name=&quot;sourceFileRef&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}IDREF&quot; /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpectrumType", propOrder = { "spectrumDescription",
        "binaryDataArrayList" })
public class SpectrumType extends ParamGroupType {

	@XmlElement(required = true)
	protected SpectrumDescriptionType spectrumDescription;
	protected BinaryDataArrayListType binaryDataArrayList;
	@XmlAttribute(required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlID
	@XmlSchemaType(name = "ID")
	protected String id;
	@XmlAttribute(required = true)
	protected String nativeID;
	@XmlAttribute
	protected String spotID;
	@XmlAttribute(required = true)
	@XmlSchemaType(name = "nonNegativeInteger")
	protected BigInteger index;
	@XmlAttribute(required = true)
	protected int defaultArrayLength;
	@XmlAttribute
	@XmlIDREF
	@XmlSchemaType(name = "IDREF")
	protected Object dataProcessingRef;
	@XmlAttribute
	@XmlIDREF
	@XmlSchemaType(name = "IDREF")
	protected Object sourceFileRef;

	/**
	 * Gets the value of the binaryDataArrayList property.
	 * 
	 * @return possible object is {@link BinaryDataArrayListType }
	 * 
	 */
	public BinaryDataArrayListType getBinaryDataArrayList() {
		return this.binaryDataArrayList;
	}

	/**
	 * Gets the value of the dataProcessingRef property.
	 * 
	 * @return possible object is {@link Object }
	 * 
	 */
	public Object getDataProcessingRef() {
		return this.dataProcessingRef;
	}

	/**
	 * Gets the value of the defaultArrayLength property.
	 * 
	 */
	public int getDefaultArrayLength() {
		return this.defaultArrayLength;
	}

	/**
	 * Gets the value of the id property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * Gets the value of the index property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getIndex() {
		return this.index;
	}

	/**
	 * Gets the value of the nativeID property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNativeID() {
		return this.nativeID;
	}

	/**
	 * Gets the value of the sourceFileRef property.
	 * 
	 * @return possible object is {@link Object }
	 * 
	 */
	public Object getSourceFileRef() {
		return this.sourceFileRef;
	}

	/**
	 * Gets the value of the spectrumDescription property.
	 * 
	 * @return possible object is {@link SpectrumDescriptionType }
	 * 
	 */
	public SpectrumDescriptionType getSpectrumDescription() {
		return this.spectrumDescription;
	}

	/**
	 * Gets the value of the spotID property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSpotID() {
		return this.spotID;
	}

	/**
	 * Sets the value of the binaryDataArrayList property.
	 * 
	 * @param value
	 *            allowed object is {@link BinaryDataArrayListType }
	 * 
	 */
	public void setBinaryDataArrayList(final BinaryDataArrayListType value) {
		this.binaryDataArrayList = value;
	}

	/**
	 * Sets the value of the dataProcessingRef property.
	 * 
	 * @param value
	 *            allowed object is {@link Object }
	 * 
	 */
	public void setDataProcessingRef(final Object value) {
		this.dataProcessingRef = value;
	}

	/**
	 * Sets the value of the defaultArrayLength property.
	 * 
	 */
	public void setDefaultArrayLength(final int value) {
		this.defaultArrayLength = value;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setId(final String value) {
		this.id = value;
	}

	/**
	 * Sets the value of the index property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setIndex(final BigInteger value) {
		this.index = value;
	}

	/**
	 * Sets the value of the nativeID property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNativeID(final String value) {
		this.nativeID = value;
	}

	/**
	 * Sets the value of the sourceFileRef property.
	 * 
	 * @param value
	 *            allowed object is {@link Object }
	 * 
	 */
	public void setSourceFileRef(final Object value) {
		this.sourceFileRef = value;
	}

	/**
	 * Sets the value of the spectrumDescription property.
	 * 
	 * @param value
	 *            allowed object is {@link SpectrumDescriptionType }
	 * 
	 */
	public void setSpectrumDescription(final SpectrumDescriptionType value) {
		this.spectrumDescription = value;
	}

	/**
	 * Sets the value of the spotID property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSpotID(final String value) {
		this.spotID = value;
	}

}
