/*
 * $Id$
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.1-646
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2008.10.14 at 08:55:46 AM CEST
//

package maltcms.io.xml.mzData;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Description of the software, and the way in which it was used to generate the
 * peak list.
 * 
 * <p>
 * Java class for dataProcessingType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;dataProcessingType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element name=&quot;software&quot;&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;extension base=&quot;{}softwareType&quot;&gt;
 *               &lt;/extension&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name=&quot;processingMethod&quot; type=&quot;{}paramType&quot; minOccurs=&quot;0&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dataProcessingType", propOrder = { "software",
        "processingMethod" })
public class DataProcessingType {

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType&gt;
	 *   &lt;complexContent&gt;
	 *     &lt;extension base=&quot;{}softwareType&quot;&gt;
	 *     &lt;/extension&gt;
	 *   &lt;/complexContent&gt;
	 * &lt;/complexType&gt;
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "")
	public static class Software extends SoftwareType {

	}

	@XmlElement(required = true)
	protected DataProcessingType.Software software;

	protected ParamType processingMethod;

	/**
	 * Gets the value of the processingMethod property.
	 * 
	 * @return possible object is {@link ParamType }
	 * 
	 */
	public ParamType getProcessingMethod() {
		return this.processingMethod;
	}

	/**
	 * Gets the value of the software property.
	 * 
	 * @return possible object is {@link DataProcessingType.Software }
	 * 
	 */
	public DataProcessingType.Software getSoftware() {
		return this.software;
	}

	/**
	 * Sets the value of the processingMethod property.
	 * 
	 * @param value
	 *            allowed object is {@link ParamType }
	 * 
	 */
	public void setProcessingMethod(final ParamType value) {
		this.processingMethod = value;
	}

	/**
	 * Sets the value of the software property.
	 * 
	 * @param value
	 *            allowed object is {@link DataProcessingType.Software }
	 * 
	 */
	public void setSoftware(final DataProcessingType.Software value) {
		this.software = value;
	}

}
