/* 
 * Maltcms, modular application toolkit for chromatography-mass spectrometry. 
 * Copyright (C) 2008-2012, The authors of Maltcms. All rights reserved.
 *
 * Project website: http://maltcms.sf.net
 *
 * Maltcms may be used under the terms of either the
 *
 * GNU Lesser General Public License (LGPL)
 * http://www.gnu.org/licenses/lgpl.html
 *
 * or the
 *
 * Eclipse Public License (EPL)
 * http://www.eclipse.org/org/documents/epl-v10.php
 *
 * As a user/recipient of Maltcms, you may choose which license to receive the code 
 * under. Certain files or entire directories may not be covered by this 
 * dual license, but are subject to licenses compatible to both LGPL and EPL.
 * License exceptions are explicitly declared in all relevant files or in a 
 * LICENSE file in the relevant directories.
 *
 * Maltcms is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. Please consult the relevant license documentation
 * for details.
 */
package maltcms.ui.wizard;

import org.netbeans.spi.wizard.WizardPage;

/**
 *
 * @author Nils.Hoffmann@cebitec.uni-bielefeld.de
 */
public class VisualizationPane extends WizardPage {

    /**
     *
     */
    private static final long serialVersionUID = 1009564289591217777L;

    public static String getDescription() {
        return "Visualization";
    }

    /**
     * Creates new form VisualizationPane
     */
    public VisualizationPane() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jCheckBox1 = new javax.swing.JCheckBox();
		jCheckBox2 = new javax.swing.JCheckBox();
		jCheckBox3 = new javax.swing.JCheckBox();
		jCheckBox4 = new javax.swing.JCheckBox();
		jCheckBox5 = new javax.swing.JCheckBox();
		jComboBox1 = new javax.swing.JComboBox();
		jLabel1 = new javax.swing.JLabel();
		jCheckBox6 = new javax.swing.JCheckBox();
		jTextField1 = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jTextField3 = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		jTextField4 = new javax.swing.JTextField();

		setBorder(javax.swing.BorderFactory
		        .createTitledBorder("Create Pairwise Alignment Charts"));
		setPreferredSize(new java.awt.Dimension(450, 300));

		jCheckBox1.setSelected(true);
		jCheckBox1.setText("Differential Chart");
		jCheckBox1
		        .setName("maltcms.commands.fragments.visualization.PairwiseAlignmentVisualizer.createDifferentialTICChart");
		jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox1ActionPerformed(evt);
			}
		});

		jCheckBox2.setSelected(true);
		jCheckBox2.setText("Ratio Chart");
		jCheckBox2
		        .setName("maltcms.commands.fragments.visualization.PairwiseAlignmentVisualizer.createRatioTICChart");
		jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox2ActionPerformed(evt);
			}
		});

		jCheckBox3.setSelected(true);
		jCheckBox3.setText("Superimposed Chart");
		jCheckBox3
		        .setName("maltcms.commands.fragments.visualization.PairwiseAlignmentVisualizer.createSuperimposedTICChart");
		jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox3ActionPerformed(evt);
			}
		});

		jCheckBox4.setSelected(true);
		jCheckBox4.setText("Comparative Chart");
		jCheckBox4
		        .setName("maltcms.commands.fragments.visualization.PairwiseAlignmentVisualizer.createComparativeTICChart");
		jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox4ActionPerformed(evt);
			}
		});

		jCheckBox5.setSelected(true);
		jCheckBox5.setText("Alignment Map Chart");
		jCheckBox5
		        .setName("maltcms.commands.fragments.visualization.PairwiseAlignmentVisualizer.createMapTICChart");
		jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox5ActionPerformed(evt);
			}
		});

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
		        "jpg", "png", "svg" }));
		jComboBox1.setName("maltcms.ui.charts.PlotRunner.filetype");
		jComboBox1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox1ActionPerformed(evt);
			}
		});

		jLabel1.setText("File Format");

		jCheckBox6.setText("Serialize JFreeChart");
		jCheckBox6
		        .setToolTipText("Serialization preserves the state of the chart. Allows later loading and editing.");
		jCheckBox6.setName("maltcms.ui.charts.PlotRunner.serializeJFreeChart");
		jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox6ActionPerformed(evt);
			}
		});

		jTextField1.setText("1024");
		jTextField1.setName("images.width");
		jTextField1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField1ActionPerformed(evt);
			}
		});

		jLabel2.setText("Width");

		jTextField2.setText("768");
		jTextField2.setName("images.height");
		jTextField2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField2ActionPerformed(evt);
			}
		});

		jLabel3.setText("Height");

		jLabel4.setText("Visualize Masses");

		jTextField3.setText("73.0,120.0,150.0");
		jTextField3
		        .setToolTipText("Enter comma separated list of double values (e.g. as 73.05), will plot the corresponding masses before and after alignment");
		jTextField3.setName("cross.tools.ImageTools.drawEICs"); // NOI18N
		jTextField3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField3ActionPerformed(evt);
			}
		});

		jLabel5.setText("Mass Visualization binsize");

		jTextField4.setText("1.0");
		jTextField4
		        .setToolTipText("Bin size to consider, starting from each mass defined above, ending at mass+binsize (exclusive)");
		jTextField4.setName("cross.tools.ImageTools.eicBinSize"); // NOI18N
		jTextField4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField4ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout
		        .setHorizontalGroup(layout
		                .createParallelGroup(
		                        javax.swing.GroupLayout.Alignment.LEADING)
		                .addGroup(
		                        layout
		                                .createSequentialGroup()
		                                .addContainerGap()
		                                .addGroup(
		                                        layout
		                                                .createParallelGroup(
		                                                        javax.swing.GroupLayout.Alignment.LEADING)
		                                                .addGroup(
		                                                        layout
		                                                                .createSequentialGroup()
		                                                                .addComponent(
		                                                                        jCheckBox5)
		                                                                .addContainerGap())
		                                                .addGroup(
		                                                        layout
		                                                                .createSequentialGroup()
		                                                                .addGap(
		                                                                        34,
		                                                                        34,
		                                                                        34)
		                                                                .addComponent(
		                                                                        jLabel2)
		                                                                .addPreferredGap(
		                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                                                                .addComponent(
		                                                                        jTextField1,
		                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
		                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
		                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
		                                                                .addPreferredGap(
		                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                                                                .addComponent(
		                                                                        jLabel3)
		                                                                .addPreferredGap(
		                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                                                                .addComponent(
		                                                                        jTextField2,
		                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
		                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
		                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
		                                                                .addGap(
		                                                                        565,
		                                                                        565,
		                                                                        565))
		                                                .addGroup(
		                                                        javax.swing.GroupLayout.Alignment.TRAILING,
		                                                        layout
		                                                                .createSequentialGroup()
		                                                                .addGroup(
		                                                                        layout
		                                                                                .createParallelGroup(
		                                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
		                                                                                .addComponent(
		                                                                                        jCheckBox1,
		                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
		                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
		                                                                                        Short.MAX_VALUE)
		                                                                                .addComponent(
		                                                                                        jCheckBox2,
		                                                                                        javax.swing.GroupLayout.Alignment.LEADING,
		                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
		                                                                                        141,
		                                                                                        Short.MAX_VALUE))
		                                                                .addPreferredGap(
		                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                                                                .addGroup(
		                                                                        layout
		                                                                                .createParallelGroup(
		                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
		                                                                                .addComponent(
		                                                                                        jCheckBox4)
		                                                                                .addComponent(
		                                                                                        jCheckBox3,
		                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
		                                                                                        179,
		                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
		                                                                .addGap(
		                                                                        471,
		                                                                        471,
		                                                                        471))
		                                                .addGroup(
		                                                        layout
		                                                                .createSequentialGroup()
		                                                                .addGroup(
		                                                                        layout
		                                                                                .createParallelGroup(
		                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
		                                                                                .addGroup(
		                                                                                        layout
		                                                                                                .createSequentialGroup()
		                                                                                                .addComponent(
		                                                                                                        jLabel1)
		                                                                                                .addPreferredGap(
		                                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                                                                                                .addComponent(
		                                                                                                        jComboBox1,
		                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
		                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
		                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
		                                                                                                .addPreferredGap(
		                                                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
		                                                                                                .addComponent(
		                                                                                                        jCheckBox6)
		                                                                                                .addPreferredGap(
		                                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
		                                                                                                        11,
		                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
		                                                                                .addGroup(
		                                                                                        layout
		                                                                                                .createSequentialGroup()
		                                                                                                .addComponent(
		                                                                                                        jLabel5)
		                                                                                                .addPreferredGap(
		                                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                                                                                                .addComponent(
		                                                                                                        jTextField4,
		                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
		                                                                                                        144,
		                                                                                                        Short.MAX_VALUE))
		                                                                                .addGroup(
		                                                                                        layout
		                                                                                                .createSequentialGroup()
		                                                                                                .addComponent(
		                                                                                                        jLabel4)
		                                                                                                .addGap(
		                                                                                                        18,
		                                                                                                        18,
		                                                                                                        18)
		                                                                                                .addComponent(
		                                                                                                        jTextField3,
		                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
		                                                                                                        196,
		                                                                                                        Short.MAX_VALUE)))
		                                                                .addGap(
		                                                                        471,
		                                                                        471,
		                                                                        471)))));
		layout
		        .setVerticalGroup(layout
		                .createParallelGroup(
		                        javax.swing.GroupLayout.Alignment.LEADING)
		                .addGroup(
		                        layout
		                                .createSequentialGroup()
		                                .addContainerGap()
		                                .addGroup(
		                                        layout
		                                                .createParallelGroup(
		                                                        javax.swing.GroupLayout.Alignment.BASELINE)
		                                                .addComponent(
		                                                        jCheckBox1)
		                                                .addComponent(
		                                                        jCheckBox4))
		                                .addPreferredGap(
		                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                                .addGroup(
		                                        layout
		                                                .createParallelGroup(
		                                                        javax.swing.GroupLayout.Alignment.BASELINE)
		                                                .addComponent(
		                                                        jCheckBox2)
		                                                .addComponent(
		                                                        jCheckBox3))
		                                .addPreferredGap(
		                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                                .addComponent(jCheckBox5)
		                                .addPreferredGap(
		                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                                .addGroup(
		                                        layout
		                                                .createParallelGroup(
		                                                        javax.swing.GroupLayout.Alignment.BASELINE)
		                                                .addComponent(
		                                                        jTextField1,
		                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
		                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
		                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
		                                                .addComponent(jLabel2)
		                                                .addComponent(
		                                                        jTextField2,
		                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
		                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
		                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
		                                                .addComponent(jLabel3))
		                                .addPreferredGap(
		                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                                .addGroup(
		                                        layout
		                                                .createParallelGroup(
		                                                        javax.swing.GroupLayout.Alignment.BASELINE)
		                                                .addComponent(
		                                                        jComboBox1,
		                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
		                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
		                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
		                                                .addComponent(jLabel1)
		                                                .addComponent(
		                                                        jCheckBox6))
		                                .addPreferredGap(
		                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                                .addGroup(
		                                        layout
		                                                .createParallelGroup(
		                                                        javax.swing.GroupLayout.Alignment.BASELINE)
		                                                .addComponent(jLabel4)
		                                                .addComponent(
		                                                        jTextField3,
		                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
		                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
		                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
		                                .addPreferredGap(
		                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                                .addGroup(
		                                        layout
		                                                .createParallelGroup(
		                                                        javax.swing.GroupLayout.Alignment.BASELINE)
		                                                .addComponent(jLabel5)
		                                                .addComponent(
		                                                        jTextField4,
		                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
		                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
		                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
		                                .addContainerGap(
		                                        javax.swing.GroupLayout.DEFAULT_SIZE,
		                                        Short.MAX_VALUE)));
	}// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jComboBox1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jCheckBox5ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField2ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jCheckBox2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField4ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jCheckBox6ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jCheckBox6ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField3ActionPerformed
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JCheckBox jCheckBox1;
	private javax.swing.JCheckBox jCheckBox2;
	private javax.swing.JCheckBox jCheckBox3;
	private javax.swing.JCheckBox jCheckBox4;
	private javax.swing.JCheckBox jCheckBox5;
	private javax.swing.JCheckBox jCheckBox6;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	// End of variables declaration//GEN-END:variables
}
