/*
 * $Id: AdminType.java 43 2009-10-16 17:22:55Z nilshoffmann $
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.1-646
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2008.10.14 at 08:55:46 AM CEST
//

package maltcms.io.xml.mzData;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 'Header' information - sample description, contact details, comments
 * 
 * <p>
 * Java class for adminType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;adminType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element name=&quot;sampleName&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *         &lt;element name=&quot;sampleDescription&quot; type=&quot;{}descriptionType&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element name=&quot;sourceFile&quot; type=&quot;{}sourceFileType&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element name=&quot;contact&quot; type=&quot;{}personType&quot; maxOccurs=&quot;unbounded&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "adminType", propOrder = { "sampleName", "sampleDescription",
        "sourceFile", "contact" })
public class AdminType {

	@XmlElement(required = true)
	protected String sampleName;
	protected DescriptionType sampleDescription;
	protected SourceFileType sourceFile;
	@XmlElement(required = true)
	protected List<PersonType> contact;

	/**
	 * Gets the value of the contact property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the contact property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getContact().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link PersonType }
	 * 
	 * 
	 */
	public List<PersonType> getContact() {
		if (this.contact == null) {
			this.contact = new ArrayList<PersonType>();
		}
		return this.contact;
	}

	/**
	 * Gets the value of the sampleDescription property.
	 * 
	 * @return possible object is {@link DescriptionType }
	 * 
	 */
	public DescriptionType getSampleDescription() {
		return this.sampleDescription;
	}

	/**
	 * Gets the value of the sampleName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSampleName() {
		return this.sampleName;
	}

	/**
	 * Gets the value of the sourceFile property.
	 * 
	 * @return possible object is {@link SourceFileType }
	 * 
	 */
	public SourceFileType getSourceFile() {
		return this.sourceFile;
	}

	/**
	 * Sets the value of the sampleDescription property.
	 * 
	 * @param value
	 *            allowed object is {@link DescriptionType }
	 * 
	 */
	public void setSampleDescription(final DescriptionType value) {
		this.sampleDescription = value;
	}

	/**
	 * Sets the value of the sampleName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSampleName(final String value) {
		this.sampleName = value;
	}

	/**
	 * Sets the value of the sourceFile property.
	 * 
	 * @param value
	 *            allowed object is {@link SourceFileType }
	 * 
	 */
	public void setSourceFile(final SourceFileType value) {
		this.sourceFile = value;
	}

}
